services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: herramientasd-springboot:local
    ports:
      - "8080:8080"
    environment:
      SPRING_THYMELEAF_CACHE: "true"
    restart: unless-stopped
