version: '3.8'

services:
  # Servicio 1: La Base de Datos PostgreSQL
  postgres-db:
    image: postgres:16-alpine
    container_name: mi_postgres_db
    environment:
      POSTGRES_DB: Proyecto_HDesarrollo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio 2: Tu aplicación Spring Boot
  backend:
    build: .
    container_name: mi_backend_app
    ports:
      - "8080:8080"
    environment:
      # El host es 'postgres-db' (el nombre del servicio de arriba)
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/Proyecto_HDesarrollo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secretpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres-db

volumes:
  postgres_data: